### ISSUE TITLE
A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@5c56a117

### ISSUE THREAD

**Issue by MrAnrehah** [bivashy/MC-Auth-with-Link#102]
After removing the plugin, everything works fine. Please correct the error. The error occurs with update 1.20.2 waterfall
```
[14:56:06 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@5c56a117
java.lang.IllegalStateException: Cancelled ServerConnectEvent with no server or disconnect.
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:340) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:321) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:298) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:291) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.connection.InitialHandler.finish2(InitialHandler.java:666) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.connection.InitialHandler.access$1300(InitialHandler.java:76) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:636) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
``` 
Before I turned here, I wrote to the Waterfall developers:
https://github.com/PaperMC/Waterfall/issues/824

**Comment by bivashy** [comment]
Partially related to #75

**Comment by MrAnrehah** [comment]
I would like to fix this bug faster, because I can't log in to the server itself.

**Comment by bivashy** [comment]
You should define the correct server in your `config.yml` under the 'priorities' field. Let's consider that your hub is named 'hub.' Here's what's happening:

1. Waterfall sends the player to 'hub' because it is defined in the `config.yml`.
2. You have also defined 'hub' as a 'blocked-server' in the `config.yml`, causing MC-Auth to block access to the hub.
3. After blocking 'hub,' Waterfall doesn't know which server to send the player to.

To resolve this issue, you should properly configure your Waterfall `config.yml`.

> I would like to fix this bug faster, because I can't log in to the server itself.

**Comment by bivashy** [comment]
> > > I would like to fix this bug faster, because I can't log in to the server itself.
> > 
> > 
> > You should define the correct server in your `config.yml` under the 'priorities' field. Let's consider that your hub is named 'hub.' Here's what's happening:
> > 
> > 1. Waterfall sends the player to 'hub' because it is defined in the `config.yml`.
> > 2. You have also defined 'hub' as a 'blocked-server' in the `config.yml`, causing MC-Auth to block access to the hub.
> > 3. After blocking 'hub,' Waterfall doesn't know which server to send the player to.
> > 
> > To resolve this issue, you should properly configure your Waterfall `config.yml`.
> 
> blocked-servers:
> 
>     * lobby
> 
>     * server
> 
> 
> auth-servers:
> 
>     * auth
> 
> 
> game-servers:
> 
>     * lobby
> 
> 
> So I have to delete lobby c blocked-servers?
> 
> And 1 more problem, when you exit the survival server, when you enter, you appear for survival, only after that, you are teleported to lobby, checked for velocity, if you exit from survival, then when you enter, you appear in the lobby.

I meant `config.yml` of Waterfall.
```yaml
enforce_secure_profile: false
listeners:
- priorities:
  - auth
servers:
  auth:
    motd: 'Authentication server'
    address: youraddress
```

**Comment by bivashy** [comment]
Use discussion for furthermore questions: https://github.com/bivashy/MC-Auth-with-Link/discussions/103

Not the issue itself.
