### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HidensGang** [bivashy/MC-Auth-with-Link#137]
[20:51:57 ERROR]: java.sql.SQLException: Unable to run insert stmt on object me.mastercapexd.auth.database.model.AuthAccount@214d003d: INSERT INTO `mc_auth_accounts` (`player_id` ,`player_id_type` ,`hash_type` ,`last_ip` ,`unique_id` ,`player_name` ,`password_hash` ,`last_quit` ,`last_session_start` ) VALUES (?,?,?,?,?,?,?,?,?)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:139)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:464)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:337)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.dao.BaseDaoImpl.createIfNotExists(BaseDaoImpl.java:381)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.dao.AuthAccountDao.lambda$createOrUpdateAccount$6(AuthAccountDao.java:161)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.dao.SupplierExceptionCatcher.execute(SupplierExceptionCatcher.java:6)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.dao.SupplierExceptionCatcher.execute(SupplierExceptionCatcher.java:14)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.dao.AuthAccountDao.createOrUpdateAccount(AuthAccountDao.java:161)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.AuthAccountDatabaseProxy.lambda$saveOrUpdateAccount$6(AuthAccountDatabaseProxy.java:67)
[20:51:57 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[20:51:57 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[20:51:57 ERROR]: Caused by: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
[20:51:57 ERROR]:       at org.sqlite.jdbc3.JDBC3PreparedStatement.unsupported(JDBC3PreparedStatement.java:448)
[20:51:57 ERROR]:       at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:357)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:188)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[20:51:57 ERROR]:       ... 10 more
[20:51:57 ERROR]: java.sql.SQLException: Unable to run insert stmt on object me.mastercapexd.auth.database.model.AuthAccount@214d003d: INSERT INTO `mc_auth_accounts` (`player_id` ,`player_id_type` ,`hash_type` ,`last_ip` ,`unique_id` ,`player_name` ,`password_hash` ,`last_quit` ,`last_session_start` ) VALUES (?,?,?,?,?,?,?,?,?)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:139)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:464)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:337)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.dao.BaseDaoImpl.createIfNotExists(BaseDaoImpl.java:381)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.dao.AuthAccountDao.lambda$createOrUpdateAccount$6(AuthAccountDao.java:161)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.dao.SupplierExceptionCatcher.execute(SupplierExceptionCatcher.java:6)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.dao.SupplierExceptionCatcher.execute(SupplierExceptionCatcher.java:14)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.dao.AuthAccountDao.createOrUpdateAccount(AuthAccountDao.java:161)
[20:51:57 ERROR]:       at me.mastercapexd.auth.database.AuthAccountDatabaseProxy.lambda$saveOrUpdateAccount$6(AuthAccountDatabaseProxy.java:67)
[20:51:57 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[20:51:57 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
[20:51:57 ERROR]: Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: mc_auth_accounts.player_id)
[20:51:57 ERROR]:       at org.sqlite.core.DB.newSQLException(DB.java:1179)
[20:51:57 ERROR]:       at org.sqlite.core.DB.newSQLException(DB.java:1190)
[20:51:57 ERROR]:       at org.sqlite.core.DB.execute(DB.java:985)
[20:51:57 ERROR]:       at org.sqlite.core.DB.executeUpdate(DB.java:1054)
[20:51:57 ERROR]:       at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:122)
[20:51:57 ERROR]:       at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:455)
[20:51:57 ERROR]:       at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:121)
[20:51:57 ERROR]:       at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:185)
[20:51:57 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[20:51:57 ERROR]:       ... 10 more

**Comment by bivashy** [comment]
Plugin version?
Proxy specs/version?
How to reproduce?
Any screenshot/additional context?

**Comment by bivashy** [comment]
No response, reopen if you have more information
