### ISSUE TITLE
На velocity

### ISSUE THREAD

**Issue by OurLobanov** [bivashy/MC-Auth-with-Link#186]
[11:57:52 INFO]: 2024-06-29 11:57:52,910 [WARNING] SqliteDatabaseType Driver class was not found for SQLite database.  Class not found: org.sqlite.JDBC
[11:57:52 ERROR]: java.sql.SQLException: No suitable driver
[11:57:52 ERROR]:       at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:300)
[11:57:52 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.BaseJdbcConnectionSource.initialize(BaseJdbcConnectionSource.java:104)
[11:57:52 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.initialize(JdbcPooledConnectionSource.java:88)
[11:57:52 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcConnectionSource.<init>(JdbcConnectionSource.java:104)
[11:57:52 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.<init>(JdbcPooledConnectionSource.java:83)
[11:57:52 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.<init>(JdbcPooledConnectionSource.java:78)
[11:57:52 ERROR]:       at me.mastercapexd.auth.database.DatabaseHelper.lambda$new$2(DatabaseHelper.java:70)
[11:57:52 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:57:52 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:57:52 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by bivashy** [comment]
SQLite driver didn't load, we need more info.

**Comment by OurLobanov** [comment]
> SQLite driver didn't load, we need more info.

I have nothing more not to withdraw

**Comment by OurLobanov** [comment]
`[12:51:33 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-9d25d309-b400)...
[12:51:33 INFO]: Loading localizations...
[12:51:33 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 3.0.x (Linux x86_64) ciphers
[12:51:33 INFO]: Loading plugins...
[12:51:33 INFO]: Loaded plugin mcauth 1.8.0-beta.1 by bivashy
[12:51:33 INFO]: Loaded 1 plugins
[12:51:33 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:28577
[12:51:33 INFO]: Done (0.85s)!
[12:51:34 INFO]: 2024-06-29 12:51:34,117 [WARNING] SqliteDatabaseType Driver class was not found for SQLite database.  Class not found: org.sqlite.JDBC
[12:51:34 ERROR]: java.sql.SQLException: No suitable driver
[12:51:34 ERROR]:       at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:300)
[12:51:34 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.BaseJdbcConnectionSource.initialize(BaseJdbcConnectionSource.java:104)
[12:51:34 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.initialize(JdbcPooledConnectionSource.java:88)
[12:51:34 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcConnectionSource.<init>(JdbcConnectionSource.java:104)
[12:51:34 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.<init>(JdbcPooledConnectionSource.java:83)
[12:51:34 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.<init>(JdbcPooledConnectionSource.java:78)
[12:51:34 ERROR]:       at me.mastercapexd.auth.database.DatabaseHelper.lambda$new$2(DatabaseHelper.java:70)
[12:51:34 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:51:34 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:51:34 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by bivashy** [comment]
`java.lang.NoClassDefFoundError: com/bivashy/auth/api/server/ServerCore`
Plugin was compiled incorrectly.

**Comment by OurLobanov** [comment]
I don’t know why I can’t compile, I pressed cleaner package again

**Comment by bivashy** [comment]
> I don’t know why I can’t compile, I pressed cleaner package again

This may happen because:
1. You've compiled without using `package` keyword.
2. You've compiled, but used wrong JAR. Original JAR size aroung ~5MB.
3. You're not deleted your old JAR from `plugins` folder.

**Comment by OurLobanov** [comment]
https://mega.nz/file/qrQVkTbb#D_qZjV_3oSJJa48HLATE4gaOHYLpv5m7pgt0CjZbo2g Here's what I got I’m not on the computer right now, I’ll be able to try again in about 5 hours

**Comment by bivashy** [comment]
> https://mega.nz/file/qrQVkTbb#D_qZjV_3oSJJa48HLATE4gaOHYLpv5m7pgt0CjZbo2g Here's what I got I’m not on the computer right now, I’ll be able to try again in about 5 hours

Your JAR size is "734 KB", it should be larger. You're probably modified `pom.xml`, or used wrong lifecycle (instead of `package`).
As I've said you're probably compiled without package keyword. You should share steps to reproduce, because i couldn't reproduce that in **main** branch.

If possible, create discussion thread instead of Issue.

**Comment by OurLobanov** [comment]
![image](https://github.com/bivashy/MC-Auth-with-Link/assets/114523572/a2ec146c-425c-4f9c-be45-ca79097d14f3)
![image](https://github.com/bivashy/MC-Auth-with-Link/assets/114523572/34be389f-35ae-4725-9291-e07fd53a22c6)
[17:25:01 INFO]: 2024-06-29 17:25:01,003 [WARNING] SqliteDatabaseType Driver class was not found for SQLite database.  Class not found: org.sqlite.JDBC
[17:25:01 ERROR]: java.sql.SQLException: No suitable driver
[17:25:01 ERROR]:       at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:300)
[17:25:01 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.BaseJdbcConnectionSource.initialize(BaseJdbcConnectionSource.java:104)
[17:25:01 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.initialize(JdbcPooledConnectionSource.java:88)
[17:25:01 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcConnectionSource.<init>(JdbcConnectionSource.java:104)
[17:25:01 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.<init>(JdbcPooledConnectionSource.java:83)
[17:25:01 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.<init>(JdbcPooledConnectionSource.java:78)
[17:25:01 ERROR]:       at me.mastercapexd.auth.database.DatabaseHelper.lambda$new$2(DatabaseHelper.java:70)
[17:25:01 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[17:25:01 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[17:25:01 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
![image](https://github.com/bivashy/MC-Auth-with-Link/assets/114523572/dedd0452-a1e8-4c10-9d6f-4c8dc3e8105c)


> > https://mega.nz/file/qrQVkTbb#D_qZjV_3oSJJa48HLATE4gaOHYLpv5m7pgt0CjZbo2g Here's what I got I’m not on the computer right now, I’ll be able to try again in about 5 hours
> 
> Your JAR size is "734 KB", it should be larger. You're probably modified `pom.xml`, or used wrong lifecycle (instead of `package`). As I've said you're probably compiled without package keyword. You should share steps to reproduce, because i couldn't reproduce that in **main** branch.
> 
> If possible, create discussion thread instead of Issue.

**Comment by bivashy** [comment]
Reproduced with specific SQLite version:
```lua
[23:06:41 ERROR]: java.util.ServiceConfigurationError: java.sql.Driver: Provider org.sqlite.JDBC could not be instantiated
[23:06:41 ERROR]: 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
[23:06:41 ERROR]: 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
[23:06:41 ERROR]: 	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
[23:06:41 ERROR]: 	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
[23:06:41 ERROR]: 	at me.mastercapexd.auth.util.DriverUtil.loadDriver(DriverUtil.java:42)
[23:06:41 ERROR]: 	at me.mastercapexd.auth.util.DriverUtil.loadDriver(DriverUtil.java:26)
[23:06:41 ERROR]: 	at me.mastercapexd.auth.database.DatabaseHelper.lambda$new$2(DatabaseHelper.java:65)
[23:06:41 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:06:41 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:06:41 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[23:06:41 ERROR]: Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
[23:06:41 ERROR]: 	at org.sqlite.JDBC.<clinit>(JDBC.java:26)
[23:06:41 ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:06:41 ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[23:06:41 ERROR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:06:41 ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[23:06:41 ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[23:06:41 ERROR]: 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
[23:06:41 ERROR]: 	... 8 more
[23:06:41 ERROR]: Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
[23:06:41 ERROR]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[23:06:41 ERROR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[23:06:41 ERROR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[23:06:41 ERROR]: 	... 15 more
```

Related: https://github.com/xerial/sqlite-jdbc/discussions/987#discussioncomment-7280381

**Comment by bivashy** [comment]
Use older sqlite-jdbc version as temporary fix.

**Comment by bivashy** [comment]
### To reproduce:
1. Download latest Velocity (Velocity 3.3.0-SNAPSHOT (git-9d25d309-b400))
2. Use SQLite
3. You'll see error in console

### Description:
Current assumption: Velocity uses newer slf4j (2.0.0 or newer), but it conflicts with SQLite's slf4j version (1.7.36). Currently best way is using LibraryManager for relocating and downloading SQLite as library

**Comment by bivashy** [comment]
Feel free to open PR with fix (without downgrading SQLite, because of #152)

**Comment by OurLobanov** [comment]
[11:34:23 INFO]: 2024-07-02 11:34:23,371 [WARNING] MysqlDatabaseType Driver class was not found for MySQL database.  Class not found: com.mysql.cj.jdbc.Driver
[11:34:23 INFO]: 2024-07-02 11:34:23,371 [WARNING] MysqlDatabaseType Driver class was not found for MySQL database.  Class not found: com.mysql.jdbc.Driver
[11:34:23 ERROR]: java.sql.SQLException: Access denied for user 'root'@'localhost'
[11:34:23 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[11:34:23 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[11:34:23 ERROR]:       at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[11:34:23 ERROR]:       at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
[11:34:23 ERROR]:       at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[11:34:23 ERROR]:       at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[11:34:23 ERROR]:       at me.mastercapexd.auth.util.DriverUtil$DelegatingDriver.connect(DriverUtil.java:67)
[11:34:23 ERROR]:       at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
[11:34:23 ERROR]:       at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:191)
[11:34:23 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:139)
[11:34:23 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.jdbc.JdbcPooledConnectionSource.getReadWriteConnection(JdbcPooledConnectionSource.java:139)
[11:34:23 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:369)
[11:34:23 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:356)
[11:34:23 ERROR]:       at com.bivashy.auth.lib.com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:99)
[11:34:23 ERROR]:       at me.mastercapexd.auth.database.dao.AccountLinkDao.<init>(AccountLinkDao.java:38)
[11:34:23 ERROR]:       at me.mastercapexd.auth.database.DatabaseHelper.lambda$new$2(DatabaseHelper.java:73)
[11:34:23 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:34:23 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:34:23 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583) 

also stands out mysql could you check maybe i have some problem

**Comment by bivashy** [comment]
> Access denied for user 'root'@'localhost'

Misconfiguration of MySQL, not related.
Please do not flood in that issue thread, create another issue instead
